# Second Partial Exam Question 6
## Arturo Fornés Arvayo A01227071

In [40]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
import pandas as pd
from sklearn.metrics import confusion_matrix

In [2]:
iris = pd.read_csv("iris_shorted.csv")

In [3]:
iris.head()

Run  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width      Species
0    1           5.1          3.3           1.7          0.5  Iris-setosa
1    2           4.4          3.2           1.3          0.2  Iris-setosa
2    3           5.4          3.4           1.7          0.2  Iris-setosa
3    4           5.1          3.8           1.5          0.3  Iris-setosa
4    5           4.9          3.0           1.4          0.2  Iris-setosa

In [8]:
iris = iris.drop("Run", axis=1)

In [9]:
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width      Species
0           5.1          3.3           1.7          0.5  Iris-setosa
1           4.4          3.2           1.3          0.2  Iris-setosa
2           5.4          3.4           1.7          0.2  Iris-setosa
3           5.1          3.8           1.5          0.3  Iris-setosa
4           4.9          3.0           1.4          0.2  Iris-setosa

In [26]:
iris.tail()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width         Species
25           6.8          3.0           5.5          2.1  Iris-virginica
26           7.9          3.8           6.4          2.0  Iris-virginica
27           6.9          3.1           5.1          2.3  Iris-virginica
28           6.4          2.7           5.3          1.9  Iris-virginica
29           6.9          3.1           5.4          2.1  Iris-virginica

In [11]:
shuffled = iris.sample(frac=1).reset_index(drop=True)

In [12]:
shuffled.head(10)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width          Species
0           4.9          2.4           3.3          1.0  Iris-versicolor
1           7.2          3.6           6.1          2.5   Iris-virginica
2           6.3          3.4           5.6          2.4   Iris-virginica
3           6.7          3.0           5.0          1.7  Iris-versicolor
4           7.9          3.8           6.4          2.0   Iris-virginica
5           4.9          3.0           1.4          0.2      Iris-setosa
6           5.7          2.6           3.5          1.0  Iris-versicolor
7           6.6          2.9           4.6          1.3  Iris-versicolor
8           6.9          3.1           5.1          2.3   Iris-virginica
9           6.8          3.0           5.5          2.1   Iris-virginica

In [35]:
# Number of rows to be used for test each iteration.
iter_size = len(shuffled)/5
iter_size

6.0

In [38]:
# Number of neighbors
np.round(np.sqrt(len(shuffled)))

5.0

In [39]:
knn = KNeighborsClassifier(n_neighbors=5)

In [56]:
iter_size = len(shuffled)//5
start = 0
avg_accuracy = 0

while start < len(shuffled):
    end = start + 5
    test = shuffled.iloc[start:end+1]
    train = shuffled.drop(shuffled.index[start:end+1])
    y_test = test["Species"]
    x_test = test.drop("Species", axis=1)
    y_train = train["Species"]
    x_train = train.drop("Species", axis=1)
    y_pred = knn.fit(x_train, y_train).predict(x_test)
    score = knn.score(x_test, y_test)
    cnf_matrix = confusion_matrix(y_test, y_pred)
    true_predictions = cnf_matrix[0][0] + cnf_matrix[1][1] + cnf_matrix[2][2]
    accuracy = true_predictions / iter_size
    print("Accuracy: ", accuracy)
    print("Score: ", score)
    print("Confusion Matrix: \n", cnf_matrix, "\n")
    avg_accuracy += accuracy
    start += iter_size

avg_accuracy /= iter_size
print("Average Accuracy: ", avg_accuracy)

Accuracy:  0.8333333333333334
Score:  0.8333333333333334
Confusion Matrix: 
 [[1 0 0]
 [0 1 1]
 [0 0 3]] 

Accuracy:  1.0
Score:  1.0
Confusion Matrix: 
 [[2 0 0]
 [0 2 0]
 [0 0 2]] 

Accuracy:  1.0
Score:  1.0
Confusion Matrix: 
 [[4 0 0]
 [0 1 0]
 [0 0 1]] 

Accuracy:  1.0
Score:  1.0
Confusion Matrix: 
 [[2 0 0]
 [0 3 0]
 [0 0 1]] 

Accuracy:  0.6666666666666666
Score:  0.6666666666666666
Confusion Matrix: 
 [[1 0 0]
 [0 1 1]
 [0 1 2]] 

Average Accuracy:  0.75
